import type { Metadata } from "next";
import "../theme/globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import antdTheme from "@/theme/antdTheme";
import { Tajawal } from "next/font/google";

const tajawal = Tajawal({
  weight: ["300", "400", "500", "700"],
  style: ["normal"],
  subsets: ["arabic"],
  display: "swap",
  variable: "--font-tajawal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = "en";
  const direction = locale === "en" ? "en" : "ar";
  return (
    <html lang={locale} dir={direction} className="dark">
      <body className={`${tajawal.variable} antialiased font-sans`}>
        <AntdRegistry>
          <ConfigProvider theme={antdTheme}>{children}</ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
